version: "3.9"
services: 
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports: 
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    container_name: flask-app
    image: duo-task-flask:latest
    build: .
    environment:
      YOUR_NAME: Ruby
      

